name: cv3d-env
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  # System related
  - python=3.8
  - pip
  - build
  - ipykernel
  - gcsfs
  - pyyaml
  - types-pyyaml
  # Scipy stack
  - numpy
  - matplotlib
  - scikit-learn
  - pandas
  # Deep learning
  - pytorch
  - torchvision
  - pytorch-cuda=11.6  # 'pytorch-cuda=11.6' if you have a gpu else 'cpuonly'
  - tensorboard
  # CV
  - opencv
  # Others
  - tqdm
  # Testing
  - pytest
  - pytest-cov
  - pytest-mock
  # Formating, linting
  - mypy
  - pylint
  - black
  - isort
  - pip:
    - open3d
    - pyrealsense2